# Import thư viện

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten, Reshape

# Đọc các biến từ file 128.ipynb

In [2]:
%store -r X
%store -r y
%store -r X_test
%store -r y_test

# Xây dựng mô hình

In [23]:
# Xây dựng mô hình
model = Sequential()

# Layer Convolutional (CNN)
model.add(Conv1D(32, kernel_size=(5), activation='relu', input_shape=(20, 128), padding='same'))
model.add(MaxPooling1D(pool_size=(2)))

# Layer LSTM
model.add(LSTM(64, activation='relu'))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(Dense(32, activation='relu'))

# Lớp Dense (có thể thay đổi theo bài toán cụ thể)
model.add(Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_6 (Conv1D)           (None, 20, 32)            20512     
                                                                 
 max_pooling1d_4 (MaxPoolin  (None, 10, 32)            0         
 g1D)                                                            
                                                                 
 lstm_7 (LSTM)               (None, 64)                24832     
                                                                 
 flatten_3 (Flatten)         (None, 64)                0         
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 5)                 165       
                                                     

# Biên dịch và huấn luyện mô hình

In [20]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=16)

Epoch 1/10
823/823 [==============================] - 8s 7ms/step - loss: 0.6555 - accuracy: 0.7494
Epoch 2/10
823/823 [==============================] - 6s 7ms/step - loss: 0.3604 - accuracy: 0.8680
Epoch 3/10
823/823 [==============================] - 6s 8ms/step - loss: 0.3005 - accuracy: 0.8858
Epoch 4/10
823/823 [==============================] - 6s 7ms/step - loss: 0.2628 - accuracy: 0.9009
Epoch 5/10
823/823 [==============================] - 6s 7ms/step - loss: 0.2341 - accuracy: 0.9123
Epoch 6/10
823/823 [==============================] - 6s 7ms/step - loss: 0.2159 - accuracy: 0.9187
Epoch 7/10
823/823 [==============================] - 6s 7ms/step - loss: 0.1988 - accuracy: 0.9240
Epoch 8/10
823/823 [==============================] - 6s 7ms/step - loss: 0.2019 - accuracy: 0.9237
Epoch 9/10
823/823 [==============================] - 6s 7ms/step - loss: 0.1710 - accuracy: 0.9337
Epoch 10/10
823/823 [==============================] - 6s 7ms/step - loss: 0.1659 - accuracy: 0.9370

# Đánh giá mô hình

In [21]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)

412/412 [==============================] - 2s 4ms/step - loss: 0.1445 - accuracy: 0.9452
Độ chính xác trên tập kiểm tra: 0.9452377557754517
412/412 [==============================] - 2s 4ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   0 1954    4   66   10]
 [   0   23 2632   13  140]
 [   0  191    8 1536    5]
 [   0   64  195    2 3481]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.88      0.96      0.92      2034
           2       0.93      0.94      0.93      2808
           3       0.95      0.88      0.92      1740
           4       0.96      0.93      0.94      3742

    accuracy                           0.95     13166
   macro avg       0.94      0.94      0.94     13166
weighted avg       0.95      0.95      0.95     13166

