In [1]:
import numpy as np

In [2]:
%store -r X
%store -r y
%store -r X_test
%store -r y_test

# Xây dựng mô hình CNN

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Khởi tạo mô hình
model = keras.Sequential()

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(20, 128, 1), padding='same'))

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5,5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(layers.Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(layers.Dense(64, activation='relu'))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp fully connected (Dense Layer) cuối cùng với số lớp đầu ra phụ thuộc vào bài toán của bạn
model.add(layers.Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()

# Biên dịch mô hình
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 20, 128, 32)       832       
                                                                 
 conv2d_1 (Conv2D)           (None, 20, 128, 32)       25632     
                                                                 
 max_pooling2d (MaxPooling2  (None, 10, 64, 32)        0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, 10, 64, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 10, 64, 64)        51264     
                                                                 
 conv2d_3 (Conv2D)           (None, 10, 64, 64)        102464    
                                                        

In [4]:
model.fit(X, y, epochs=10, validation_data=(X, y))

Epoch 1/10
412/412 [==============================] - 244s 588ms/step - loss: 0.9634 - accuracy: 0.6186 - val_loss: 0.4748 - val_accuracy: 0.8674
Epoch 2/10
412/412 [==============================] - 224s 545ms/step - loss: 0.5657 - accuracy: 0.7937 - val_loss: 0.3299 - val_accuracy: 0.8895
Epoch 3/10
412/412 [==============================] - 207s 502ms/step - loss: 0.4785 - accuracy: 0.8262 - val_loss: 0.2792 - val_accuracy: 0.8938
Epoch 4/10
412/412 [==============================] - 208s 504ms/step - loss: 0.4339 - accuracy: 0.8365 - val_loss: 0.2436 - val_accuracy: 0.9096
Epoch 5/10
412/412 [==============================] - 208s 505ms/step - loss: 0.3990 - accuracy: 0.8533 - val_loss: 0.2514 - val_accuracy: 0.9112
Epoch 6/10
412/412 [==============================] - 209s 507ms/step - loss: 0.3865 - accuracy: 0.8587 - val_loss: 0.2299 - val_accuracy: 0.9202
Epoch 7/10
412/412 [==============================] - 209s 506ms/step - loss: 0.3643 - accuracy: 0.8676 - val_loss: 0.2241 -

In [5]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)


412/412 [==============================] - 27s 66ms/step - loss: 0.1790 - accuracy: 0.9313
Độ chính xác trên tập kiểm tra: 0.9313383102416992
412/412 [==============================] - 27s 66ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   0 1998   10    1   25]
 [   0   20 2664    0  124]
 [   0  425   11 1296    8]
 [   0   16  264    0 3462]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.81      0.98      0.89      2034
           2       0.90      0.95      0.93      2808
           3       1.00      0.74      0.85      1740
           4       0.96      0.93      0.94      3742

    accuracy                           0.93     13166
   macro avg       0.93      0.92      0.92     13166
weighted avg       0.94      0.93      0.93     13166

